version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "mambaforge-22.9"

sphinx:
  configuration: docs/conf.py

formats: all

conda:
  environment: environment.yml

python:
  install:
    - method: pip
      path: .
