name: goodman_pipeline
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - scipy
  - cython
  - astropy
  - pip
  - pip:
    - ccdproc
    - coloredlogs
    - coveralls
    - astroplan
    - mock
    - sphinx
    - sphinxcontrib.napoleon
