name: goodman_pipeline
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - scipy
  - cython
  - sphinx
  - sphinxcontrib-napoleon
  - pip
  - pip:
      - astropy>=5.3
      - ccdproc
      - coveralls
      - pydata-sphinx-theme
      - astroplan
      - mock
